language: rust
rust: nightly

script:
    - cargo test -v
    - cargo build --manifest-path benchmarks/Cargo.toml -v
    - cargo run --example simple
    - cargo run --example panic
    - cargo test -v --release
    - cargo run --example simple --release
    - cargo run --example panic --release
