language: rust
rust: nightly

script:
    - RUST_BACKTRACE=1 cargo test -v
    - cargo build --manifest-path benchmarks/Cargo.toml -v
    - RUST_BACKTRACE=1 cargo run --example simple
    - RUST_BACKTRACE=1 cargo run --example panic
    - RUST_BACKTRACE=1 cargo test -v --release
    - RUST_BACKTRACE=1 cargo run --example simple --release
    - RUST_BACKTRACE=1 cargo run --example panic --release
