language: rust
rust: nightly

script:
    - cargo test -v
    - cargo build --manifest-path benchmarks/Cargo.toml -v
    - cargo run --example simple
    - cargo run --example main_function
    - cargo run --example panic
