[package]
name = "coio"
version = "0.1.2"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
description = "Coroutine scheduler with non-blocking I/O support"
repository = "https://github.com/zonyitoo/coio-rs"
keywords = ["coroutine", "fiber", "green", "green thread", "non-blocking", "io", "async"]

[lib]
name = "coio"

[dev-dependencies]
clap = "*"
env_logger = "*"
openssl = "*"
num_cpus = "*"
rand = "*"

[dependencies]
lazy_static = "^0.1.14"
log = "^0.3.1"
hyper = "^0.6.8"
url = "^0.2"
rand = "^0.3.10"
chrono = "^0.2.15"
libc = "^0.1.10"

[dependencies.deque]
git = "https://github.com/kinghajj/deque.git"

[dependencies.context]
git = "https://github.com/zonyitoo/context-rs.git"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes.git"
